FROM node:20-slim AS builder
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
WORKDIR /app

COPY apps/web/package*.json ./
RUN npm ci
COPY apps/web/tsconfig*.json ./
COPY apps/web/next.config.js ./
COPY apps/web/next-env.d.ts ./
COPY apps/web/public ./public
COPY apps/web/src ./src

RUN npm run build

FROM node:20-slim
WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./

EXPOSE 3000
CMD ["npm", "start"]
